In [2]:
import pandas as pd
from pathlib import Path

# Use your provided path, with a fallback for workspace-root execution
candidate_paths = [
    Path("../Data/gcp_order/dtu_findit/extraction_and_processing/master_thesis_metrics_analysis.csv"),
    Path("Data/gcp_order/dtu_findit/extraction_and_processing/master_thesis_metrics_analysis.csv"),
]

csv_path = next((p for p in candidate_paths if p.exists()), None)
if csv_path is None:
    raise FileNotFoundError("Could not find master_thesis_metrics_analysis.csv in expected locations.")

# File is semicolon-separated and contains some malformed rows.
metrics_df = pd.read_csv(csv_path, sep=";", engine="python", on_bad_lines="skip")
print(f"Loaded: {csv_path}")
print(f"Shape: {metrics_df.shape}")

metrics_df.head()

Loaded: ../Data/gcp_order/dtu_findit/extraction_and_processing/master_thesis_metrics_analysis.csv
Shape: (4254, 14)

,pdf_file,member_id_ss_metrics,num_tot_pages,num_cont_pages,match_trigger,num_words_full,num_words_cont,abstract_ts,Author,Publication Year,primary_member_id_s,Title,Department_new,author_count
0,5ce67fe9d9001d016b4fccc7_Experimental analysis...,5ce67fe9d9001d016b4fccc7,66,62,exact ('references'),15415,13882,Department of Chemical and Biochemical Enginee...,"Joshi, Ameya Sunil",2019,5ce67fe9d9001d016b4fccc7,Experimental analysis of CO2 vapour liquid equ...,DTU Chemical Engineering,1
1,5c7a72ffd9001d361b4cd3ec_Heart segmentation us...,5c7a72ffd9001d361b4cd3ec,84,74,"prefix-match ('appendix a', prefix='appendix')",19892,18374,"In the ﬁeld of medical imaging, a lot of resea...","Ellegaard, Andreas Høyby",2019,5c7a72ffd9001d361b4cd3ec,Heart segmentation using deep learning|Segment...,DTU Compute,1
2,5cee68eed9001d2064299318_Deep Reinforcement Le...,5cee68eed9001d2064299318,61,51,exact ('references'),20540,17924,Robotic exploration in an unknown environment ...,"Hamilton, Francis Nils",2019,5cee68eed9001d2064299318,Deep Reinforcement Learning: Applying an actor...,DTU Electro,1
3,5cf10bded9001d206429933c_Restoration of marine...,5cf10bded9001d206429933c,29,24,exact ('references'),9603,7793,Anthropogenic impacts on marine habitats are a...,"Nordfoss, Pauli Holm",2019,5cf10bded9001d206429933c,Restoration of marine boulder reefs: addressin...,DTU Aqua,1
4,5cf10bded9001d206429933f_Data augmentation of ...,5cf10bded9001d206429933f,74,72,exact ('bibliography'),10694,10338,This thesis is about a deep learning segmentat...,"Talleruphuus, Anne Sofie",2019,5cf10bded9001d206429933f,Data augmentation of CT scans|Data augmentatio...,DTU Compute,1

In [3]:
# Use your provided path, with a fallback for workspace-root execution
candidate_paths = [
    Path("../Data/gcp_order/dtu_findit/extraction_and_processing/handin_month_summary.csv"),
    Path("Data/gcp_order/dtu_findit/extraction_and_processing/handin_month_summary.csv"),
]

csv_path = next((p for p in candidate_paths if p.exists()), None)
if csv_path is None:
    raise FileNotFoundError("Could not find handin_month_summary.csv in expected locations.")

# File is semicolon-separated and contains some malformed rows.
seasonality_df = pd.read_csv(csv_path, sep=",", engine="python", on_bad_lines="skip")
print(f"Loaded: {csv_path}")
print(f"Shape: {seasonality_df.shape}")

seasonality_df.head()

Loaded: ../Data/gcp_order/dtu_findit/extraction_and_processing/handin_month_summary.csv
Shape: (6061, 2)

                                            filename extracted_month
0  5c7a72fdd9001d361b4cd3e4_Coronary atherosclero...    January 2019
1  5c7a72ffd9001d361b4cd3e8_Coronary Atherosclero...    January 2019
2  5c7a72ffd9001d361b4cd3ec_Heart segmentation us...  September 2018
3  5c7a7302d9001d361b4cd3f2_Heart segmentation us...    January 2019
4  5cdd4565d9001d016b6b0a26_Golf club detection a...        May 2019

In [4]:
merged_dfs = pd.merge(
    metrics_df,
    seasonality_df,
    left_on="pdf_file",
    right_on="filename",
    how="inner",
)

# drop the redundant 'filename' column after the merge
merged_dfs.drop(columns=["filename"], inplace=True)

# rename column "extracted_month" to "handin_month"
merged_dfs.rename(columns={"extracted_month": "handin_month"}, inplace=True)

master_thesis_metrics_analysis_v2 = merged_dfs

print(type(master_thesis_metrics_analysis_v2))
display(master_thesis_metrics_analysis_v2.head())

<class 'pandas.DataFrame'>

,pdf_file,member_id_ss_metrics,num_tot_pages,num_cont_pages,match_trigger,num_words_full,num_words_cont,abstract_ts,Author,Publication Year,primary_member_id_s,Title,Department_new,author_count,handin_month
0,5ce67fe9d9001d016b4fccc7_Experimental analysis...,5ce67fe9d9001d016b4fccc7,66,62,exact ('references'),15415,13882,Department of Chemical and Biochemical Enginee...,"Joshi, Ameya Sunil",2019,5ce67fe9d9001d016b4fccc7,Experimental analysis of CO2 vapour liquid equ...,DTU Chemical Engineering,1,NaN
1,5c7a72ffd9001d361b4cd3ec_Heart segmentation us...,5c7a72ffd9001d361b4cd3ec,84,74,"prefix-match ('appendix a', prefix='appendix')",19892,18374,"In the ﬁeld of medical imaging, a lot of resea...","Ellegaard, Andreas Høyby",2019,5c7a72ffd9001d361b4cd3ec,Heart segmentation using deep learning|Segment...,DTU Compute,1,September 2018
2,5cee68eed9001d2064299318_Deep Reinforcement Le...,5cee68eed9001d2064299318,61,51,exact ('references'),20540,17924,Robotic exploration in an unknown environment ...,"Hamilton, Francis Nils",2019,5cee68eed9001d2064299318,Deep Reinforcement Learning: Applying an actor...,DTU Electro,1,April 2019
3,5cf10bded9001d206429933c_Restoration of marine...,5cf10bded9001d206429933c,29,24,exact ('references'),9603,7793,Anthropogenic impacts on marine habitats are a...,"Nordfoss, Pauli Holm",2019,5cf10bded9001d206429933c,Restoration of marine boulder reefs: addressin...,DTU Aqua,1,May 2019
4,5cf10bded9001d206429933f_Data augmentation of ...,5cf10bded9001d206429933f,74,72,exact ('bibliography'),10694,10338,This thesis is about a deep learning segmentat...,"Talleruphuus, Anne Sofie",2019,5cf10bded9001d206429933f,Data augmentation of CT scans|Data augmentatio...,DTU Compute,1,May 2019

In [10]:
# export master_thesis_metrics_analysis_v2 to a new CSV file
output_path = Path("Data/gcp_order/dtu_findit/extraction_and_processing/master_thesis_metrics_analysis_v2.csv")
master_thesis_metrics_analysis_v2.to_csv(output_path, sep=";", index=False)
print(f"Exported merged DataFrame to: {output_path}")

Exported merged DataFrame to: Data/gcp_order/dtu_findit/extraction_and_processing/master_thesis_metrics_analysis_v2.csv

In [5]:
nan_count = master_thesis_metrics_analysis_v2["handin_month"].isna().sum()
print(f"Number of rows where 'handin_month' is NaN: {nan_count}")

Number of rows where 'handin_month' is NaN: 831

In [6]:
len(master_thesis_metrics_analysis_v2)

4056

In [1]:
display(master_thesis_metrics_analysis_v2[master_thesis_metrics_analysis_v2["handin_month"].isna()])

NameError: name 'master_thesis_metrics_analysis_v2' is not defined